import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { Metadata } from "next";
import Footer from "~/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Stell Coffee & Tea Co | Redlands, CA",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "./favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} grid h-full w-full place-items-center`}
      >
        <div className="grid w-8/12 place-items-center">
          <div className="w-full">{children}</div>
        </div>
        <footer className="h-full w-full bg-orange-550">
          <div className="grid w-8/12 place-items-center p-4">
            <Footer />
          </div>
        </footer>
      </body>
    </html>
  );
}
